# =============================================================================
# Kubernetes CRD-Based API Versioning for APISIX
# =============================================================================
# Use these CRDs when running APISIX with the Ingress Controller in Kubernetes
# =============================================================================

---
# Upstreams for different API versions
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: users-v1
  namespace: apisix
spec:
  externalNodes:
    - name: users-v1-service.default.svc.cluster.local
      port: 8080
      weight: 100
      type: Domain
  scheme: http
  timeout:
    connect: 5s
    send: 10s
    read: 10s

---
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: users-v2
  namespace: apisix
spec:
  externalNodes:
    - name: users-v2-service.default.svc.cluster.local
      port: 8080
      weight: 100
      type: Domain
  scheme: http
  timeout:
    connect: 5s
    send: 15s
    read: 15s

---
apiVersion: apisix.apache.org/v2
kind: ApisixUpstream
metadata:
  name: users-v3
  namespace: apisix
spec:
  externalNodes:
    - name: users-v3-service.default.svc.cluster.local
      port: 8080
      weight: 100
      type: Domain
  scheme: http
  timeout:
    connect: 5s
    send: 15s
    read: 15s

---
# Route: API V1 Users (Legacy)
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: api-v1-users
  namespace: apisix
  labels:
    api-version: "v1"
    status: "legacy"
spec:
  http:
    - name: v1-users
      match:
        paths:
          - /api/v1/users/*
        methods:
          - GET
          - POST
          - PUT
          - DELETE
      backends:
        - serviceName: users-v1-service
          servicePort: 8080
      plugins:
        - name: response-rewrite
          enable: true
          config:
            headers:
              set:
                X-API-Version: "1"
                X-API-Deprecated: "false"

---
# Route: API V2 Users (Current Stable)
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: api-v2-users
  namespace: apisix
  labels:
    api-version: "v2"
    status: "stable"
spec:
  http:
    - name: v2-users
      match:
        paths:
          - /api/v2/users/*
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
      backends:
        - serviceName: users-v2-service
          servicePort: 8080
      plugins:
        - name: response-rewrite
          enable: true
          config:
            headers:
              set:
                X-API-Version: "2"
                X-API-Deprecated: "false"

---
# Route: API V3 Users (Beta)
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: api-v3-users
  namespace: apisix
  labels:
    api-version: "v3"
    status: "beta"
spec:
  http:
    - name: v3-users
      match:
        paths:
          - /api/v3/users/*
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
      backends:
        - serviceName: users-v3-service
          servicePort: 8080
      plugins:
        - name: response-rewrite
          enable: true
          config:
            headers:
              set:
                X-API-Version: "3"
                X-API-Beta: "true"
                X-API-Warning: "Beta version - breaking changes may occur"

