# =============================================================================
# PRODUCTION Environment Authentication Plugin Config
# =============================================================================
# Strict authentication and authorization in production
# =============================================================================

---
apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: prod-auth-config
spec:
  plugins:
    - name: jwt-auth
      enable: true
      config:
        header: Authorization
        query: token
        cookie: jwt
    - name: consumer-restriction
      enable: true
      config:
        type: consumer_name
        whitelist:
          - prod-service-account
          - prod-admin
    - name: ip-restriction
      enable: true
      config:
        whitelist:
          - 10.0.0.0/8      # Internal network
          - 172.16.0.0/12   # Internal network
          - 192.168.0.0/16  # Internal network

