# =============================================================================
# PRODUCTION Environment Monitoring Plugin Config
# =============================================================================
# Comprehensive monitoring and logging for production
# =============================================================================

---
apiVersion: apisix.apache.org/v2
kind: ApisixPluginConfig
metadata:
  name: prod-monitoring-config
spec:
  plugins:
    - name: prometheus
      enable: true
      config:
        prefer_name: true
    - name: http-logger
      enable: true
      config:
        uri: http://logging-service.prod.svc.cluster.local:8080/logs
        batch_max_size: 100
        max_retry_count: 3
        retry_delay: 1
        buffer_duration: 60
        inactive_timeout: 5
        concat_method: json
        include_req_body: false
        include_resp_body: false
    - name: opentelemetry
      enable: true
      config:
        sampler:
          name: always_on
        additional_attributes:
          - environment
          - api_version

